### ISSUE TITLE
When will a new release be published?

### ISSUE THREAD

**Issue by JakeChampion** [paulmillr/Array.prototype.find#16]
Some changes have been added to master which have not been published as an update for the module. Would you be able to give a date for when these changes will be published?

**Comment by JakeChampion** [comment]
Would you be able to publish a new release please?

**Comment by ljharb** [comment]
@paulmillr I don't have `npm owner` on this package, or I'd take care of it - would you mind cutting a release?

**Comment by ljharb** [comment]
Published at 1454b62ff913f84e618668faaa70174e10f7a92a
