### ISSUE TITLE
How is one supposed to know that you must call shim() before using #find?

### ISSUE THREAD

**Issue by j4yk** [paulmillr/Array.prototype.find#18]
I have come to this package by googling for an Array.prototype.find polyfill, but had never heard about esX-shims, its API contracts or the term 'shim' in general before. It seems you have to call `require('array.prototype.find').shim()` instead of only the require to have `#find` actually available.

How are newcomers like me supposed to figure that out, other than by reading the code? Have I overlooked something? Did I eventually figure it out correctly? :-) I would like to either see that among the usage information in the README or have some kind of reference there to "things you are supposed to know when using those es6 polyfills".

**Comment by ljharb** [comment]
The README definitely needs updating - PRs welcome!

(However, your default assumption should be that nothing on npm modifies the environment automatically - automatically shimming the environment is legacy behavior from a pre-module world that newcomers wouldn't expect)

**Comment by j4yk** [comment]
Ok, I will keep that in mind from now on. I guess I assumed otherwise because the only other polyfill I have worked with so far was for additional markup among HTML and there it was intended that you just have to include the script to get everything going. I will see if I can come up with something for the readme. Thank you!
