### ISSUE TITLE
getPolyfill is incorrect, Array.find is always shimmed when calling .shim()

### ISSUE THREAD

**Issue by zerovox** [paulmillr/Array.prototype.find#22]
```
var implemented = Array.prototype.find && [, 1].find(function (item, index) {
	return index === 0;
});
```

The comment says 'Detect early implementations which skipped holes in sparse arrays' but this code appears to return the first item in the array, which is `undefined`, hence implemented returns false. I believe that whole clause should be negated.

**Comment by zerovox** [comment]
Indeed, it is negated in [es6-shim](https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js#L1465)

**Comment by zerovox** [comment]
I believe this bug is present in `es6-shim` too, filed [#433](https://github.com/paulmillr/es6-shim/issues/433) to track

**Comment by ljharb** [comment]
Thanks, I'll fix in both places.

**Comment by ljharb** [comment]
Released in v2.0.2

**Comment by zerovox** [comment]
Did you test this in chrome @ljharb? I'm pretty sure this fix has the exact same issue.

**Comment by ljharb** [comment]
@zerovox ah crap, you're right. I forgot the negation :-) v2.0.3 coming soon.

**Comment by ljharb** [comment]
(for the record; my tests only test for proper behavior; an overzealous shim is not an observable bug, it's simply a negligible performance hit :-) )

**Comment by zerovox** [comment]
Thanks for the quick fixes! Yep, correctness wasn't an issue but the shimmed `.find` is unfortunately slower than the native equivalent in our use case. Might be possible to test the overzealous shimming in es6-shim with a test that shims once then mocks `overrideNative` and attempts to shim a second time - `overrideNative` should, theoretically, never be called on the second iteration.

**Comment by ljharb** [comment]
That's a very interesting idea!
