### ISSUE TITLE
Performance concerns with implementation

### ISSUE THREAD

**Issue by benstepp** [paulmillr/Array.prototype.find#23]
Over [here](yannickcr/eslint-plugin-react#1126), we found that one the rules was running significantly slower to others because it utilized this package (prior to the change to use the native implementation if it exists).

A lot of the poor performance comes from the needless calls to ES abstract functions that have already been called with the same values. es-abstract has no way of internally knowing the results of previous calls, so will call them over and over.

---

#### Recommended changes

- The biggest culprit is ES.IsCallable. It is being called in the implementation on every single iteration of the loop for the same function inside of ES.Call. I would think the only away around this is to inline the `predicate.apply(thisArg, [value, i, list])` here.

- ES.CheckObjectCoercible is checked in both the `index.js` and in the ES.ToObject function inside of the implementation. These improvements are minor compared to ES.IsCallable.

- Another minor improvement could be made in the implementation. I noticed it calls ToInteger on ToLength, where the [spec](https://tc39.github.io/ecma262/#sec-array.prototype.find) only specifies that it needs to be ToLength. Note that ToLength is internally required to convert to an Integer.

- Some [leaking arguments](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#32-leaking-arguments) could be changed for better performance in v8, but I don't think it is necessary for this project, as modern v8 would just use the native implementation anyway.

After changing everything I found the implementation to improve drastically. Primarily due to the dropping of needless Es.IsCallable calls.
```
npm x 68,048 ops/sec ±1.43% (88 runs sampled)
current x 3,010,815 ops/sec ±1.60% (88 runs sampled)
implementation x 381,824 ops/sec ±1.13% (89 runs sampled)
native x 7,489,132 ops/sec ±1.33% (88 runs sampled)
for loop x 5,298,090 ops/sec ±0.91% (92 runs sampled)
```

---

As a Side note, I have an idea for a change that could improve is-callable performance thereby improving this project's performance (Even with only one call to ES.IsCallable). After inlining an idea to this project we can double the implementation's speed again. 
```
npm x 66,008 ops/sec ±1.75% (85 runs sampled)
current x 3,043,061 ops/sec ±1.32% (88 runs sampled)
implementation x 637,159 ops/sec ±1.09% (89 runs sampled)
native x 7,398,072 ops/sec ±1.35% (88 runs sampled)
for loop x 5,245,309 ops/sec ±1.08% (91 runs sampled)
```

**Comment by ljharb** [comment]
Thanks!

The double `ToObject` is actually necessary; in IE 6 - 8, the check inside `implementation` won't work when it's bound inside `index.js`.

**Comment by ljharb** [comment]
@benstepp k, pushed up some commits; let me know if the master branch is faster.

Also please feel free to file issues directly on es-abstract if you think you can help make any of those implementations faster.

**Comment by ljharb** [comment]
@benstepp ping :-)

**Comment by benstepp** [comment]
Yeah much faster, especially when given 'normal' sized array use case. 👍

The bottleneck is now in is-callable. As the array gets larger the implementation gets much closer to native methods (up to 60% same at 1000000 items).  This issue can be closed now.

<details>
  <summary>Array length 1</summary>

```
[2.0.3] only x 196,203 ops/sec ±0.73% (90 runs sampled)
[current] only x 3,751,056 ops/sec ±2.00% (89 runs sampled)
[implementation] only x 380,274 ops/sec ±1.11% (90 runs sampled)
[native] only x 20,059,953 ops/sec ±0.84% (88 runs sampled)
[for] only x 19,990,404 ops/sec ±1.17% (88 runs sampled)
```

</details>


<details>
  <summary>Array length 100, searching for index 50</summary>

```
[2.0.3] positive x 8,301 ops/sec ±1.02% (91 runs sampled)
[current] positive x 564,038 ops/sec ±1.46% (89 runs sampled)
[implementation] positive x 140,253 ops/sec ±1.34% (88 runs sampled)
[native] positive x 645,620 ops/sec ±1.28% (90 runs sampled)
[for] positive x 405,705 ops/sec ±1.05% (91 runs sampled)
```

</details>


<details>
  <summary>Array length 100, searching nothing</summary>

```
[2.0.3] negative x 4,256 ops/sec ±1.02% (91 runs sampled)
[current] negative x 315,672 ops/sec ±1.34% (89 runs sampled)
[implementation] negative x 89,447 ops/sec ±1.32% (91 runs sampled)
[native] negative x 340,653 ops/sec ±1.14% (89 runs sampled)
[for] negative x 200,809 ops/sec ±1.41% (91 runs sampled)
```

</details>


<details>
  <summary>Array length 1000000, searching nothing</summary>

```
[2.0.3] veryBig x 0.41 ops/sec ±2.25% (6 runs sampled)
[current] veryBig x 8.39 ops/sec ±2.23% (25 runs sampled)
[implementation] veryBig x 5.46 ops/sec ±0.87% (18 runs sampled)
[native] veryBig x 8.40 ops/sec ±1.69% (25 runs sampled)
[for] veryBig x 7.15 ops/sec ±1.38% (22 runs sampled)
```

</details>

**Comment by ljharb** [comment]
Thanks!
